display_name="Rosalina [c03] (Aurora)"
authors = "Hanxulz"
description="""
The end of the year is here and to celebrate Rosalina bring an stuning dress resembling the Auoras in the north pole.
"""
version="1.0.0"
category="Fighter"