display_name = "Mario Series Donkey Kong"
description = "A voice mod that changes Donkey Kong's voice clips to the ones that were made by Takashi Nagasako. The mod includes a plugin, which requires Smashline 2 to use."
version = "Any"
authors = "Mario and Sonic Guy"
category = "Audio"