kind = "lucario"
slots = [8,9,10,11,12,13,14,15]

[[param_float]]
param = "weight"
subparam = ""
value =  77.0

[[param_float]]
param = "dash_speed"
subparam = ""
value = 2.6

[[param_float]]
param = "walk_speed_max"
subparam = ""
value =  1.3

[[param_float]]
param = "run_accel_mul"
subparam = ""
value =  2.75

[[param_float]]
param = "run_accel_add"
subparam = ""
value =  2.3

[[param_float]]
param = "run_speed_max"
subparam = ""
value =  2.1

[[param_float]]
param = "air_accel_x_mul"
subparam = ""
value =  2.11

[[param_float]]
param = "air_accel_x_add"
subparam = ""
value =  2.03

[[param_float]]
param = "air_accel_x_stable"
subparam = ""
value =  1.6

[[param_float]]
param = "air_speed_x_stable"
subparam = ""
value = 1.8

[[param_float]]
param = "dive_speed_y"
subparam = ""
value =  3.5

[[param_int]]
param = "jump_count_max"
subparam = ""
value = 3

[[param_float]]
param = "jump_y"
subparam = ""
value =  40

[[param_float]]
param = "jump_aerial_y"
subparam = ""
value =  32.0

[[param_int]]
param = "jump_squat_frame"
value =  2