kind = "luigi"
slots = [16, 17, 18, 19, 20, 21, 22, 23]

[[param_float]]
param = "walk_speed_max"
subparam = ""
value =  2.0412

[[param_float]]
param = "dash_speed"
subparam = ""
value = 3.267

[[param_float]]
param = "run_speed_max"
subparam = ""
value =  2.97

[[param_float]]
param = "jump_y"
subparam = ""
value =  77.6512

[[param_float]]
param = "mini_jump_y"
subparam = ""
value =  35.260704

[[param_float]]
param = "jump_aerial_y"
subparam = ""
value =  72.9038

[[param_float]]
param = "air_speed_y_stable"
subparam = ""
value =  1.3588

[[param_float]]
param = "dive_speed_y"
subparam = ""
value =  3.7272

[[param_float]]
param = "air_accel_y"
subparam = ""
value =  0.1323
