kind = "popo"
slots = [8, 9, 10, 11, 12, 13, 14, 15]

[[param_float]]
param = "weight"
subparam = ""
value = 60

[[param_int]]
param = "jump_count_max"
subparam = ""
value = 10

[[param_float]]
param = "dash_speed"
subparam = ""
value = 1.98

[[param_float]]
param = "run_speed_max"
subparam = ""
value = 1.83

[[param_float]]
param = "walk_speed_max"
subparam = ""
value = 1.308

[[param_float]]
param = "ground_brake"
subparam = ""
value = 0.1

[[param_float]]
param = "jump_y"
subparam = ""
value =  16.5

[[param_float]]
param = "mini_jump_y"
subparam = ""
value =  8.0

[[param_float]]
param = "jump_aerial_y"
subparam = ""
value =  15.0

[[param_float]]
param = "shield_radius"
subparam = ""
value =  8.096

[[param_int]]
param = "jump_squat_frame"
value =  12