kind = "krool"
slots = [8, 9, 10, 11, 12, 13, 14, 15]

[[param_float]]
param = "weight"
value =  69.0

[[param_int]]
param = "jump_squat_frame"
value =  12

[[param_float]]
param = "air_accel_x_mul"
value =  0.1

[[param_float]]
param = "air_accel_x_add"
value =  0.08

[[param_float]]
param = "air_accel_x_stable"
subparam = ""
value =  0.8

[[param_float]]
param = "air_speed_x_stable"
value =  1.332

[[param_float]]
param = "air_brake_x"
value =  0.0375

[[param_float]]
param = "jump_y"
value =  50.51

[[param_float]]
param = "mini_jump_y"
value =  17.34

[[param_float]]
param = "dash_speed"
subparam = ""
value =  1.62

[[param_float]]
param = "run_accel_mul"
subparam = ""
value =  2.75

[[param_float]]
param = "run_accel_add"
subparam = ""
value =  2.3

[[param_float]]
param = "run_speed_max"
subparam = ""
value =  2.0

[[param_float]]
param = "walk_speed_max"
subparam = ""
value =  1.13