kind = "mario"
slots = [8, 9, 10, 11, 12, 13, 14, 15]

[[param_float]]
param = "weight"
value =  76.0

[[param_int]]
param = "jump_squat_frame"
value =  2

[[param_float]]
param = "walk_accel_mul"
value =  0.0525

[[param_float]]
param = "walk_accel_add"
value =  0.0525

[[param_float]]
param = "walk_speed_max"
value =  0.86625

[[param_float]]
param = "run_accel_mul"
value =  0.7645

[[param_float]]
param = "run_accel_add"
value =  0.033

[[param_float]]
param = "run_speed_max"
value =  1.32

[[param_float]]
param = "dash_speed"
value =  1.452

[[param_float]]
param = "air_accel_x_mul"
value =  0.14

[[param_float]]
param = "air_speed_x_stable"
value =  1.51

[[param_float]]
param = "air_accel_y"
value =  0.066

[[param_float]]
param = "air_speed_y_stable"
value =  1.234