display_name = "Mario Series Diddy Kong"
description = "A voice mod that changes Diddy Kong's voice clips to the ones that were made by Chris Sutherland and Katsumi Suzuki. The mod includes a plugin, which requires Smashline 2 to use."
version = "Any"
authors = "Mario and Sonic Guy"
category = "Audio"